name: Schema Update

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  schema-update:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Swiftly
        uses: vapor/swiftly-action@v0.2

      - name: Cache SwiftFormat
        id: cache-swiftformat
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/swiftformat
          key: ${{ runner.os }}-swiftformat-0.56.2

      - name: Install SwiftFormat
        if: steps.cache-swiftformat.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 --branch 0.56.2 https://github.com/nicklockwood/SwiftFormat.git
          cd SwiftFormat
          swift build -c release
          sudo cp .build/release/swiftformat /usr/local/bin/
          cd ..
          rm -rf SwiftFormat

      - name: Cache Swift build
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-swift-build-${{ hashFiles('Package.swift', 'Package.resolved') }}

      - name: Install quicktype
        run: |
          # Node.js is pre-installed on Ubuntu runners
          sudo npm install -g quicktype

      - name: Update schemas
        id: update
        run: |
          # Update submodules to latest
          make update

          # Generate code
          make generate

          # Check if there are any changes in generated source code (not just submodules)
          if [[ -n $(git status --porcelain Sources/) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Generated code changes detected"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No generated code changes - only submodule updates"
          fi

      - name: Create Pull Request
        if: steps.update.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            Sources/
            .dependencies/
          commit-message: |
            Update Slack API schemas

            This is an automated update of the Slack API schemas from upstream sources.

            🤖 Generated with [Claude Code](https://claude.ai/code)

            Co-Authored-By: Claude <noreply@anthropic.com>
          branch: automated/schema-update-${{ github.run_number }}
          delete-branch: true
          title: '[Automated] Update Slack API schemas'
          body: |
            ## 🤖 Automated Schema Update

            This PR contains automated updates to the Slack API schemas from the following sources:
            - `java-slack-sdk`: Sample JSON payloads
            - `slack-api-ref`: API method definitions

            ### Changes

            The following files have been updated:
            - Generated WebAPI client code
            - Generated event types
            - SlackModels shared types

            ### Review Checklist

            - [ ] Review the generated code changes
            - [ ] Ensure all tests pass
            - [ ] Check for any breaking API changes
            - [ ] Verify the generated code compiles successfully

            ---

            *This PR was automatically generated by the schema update workflow.*
          labels: |
            automated
            dependencies
            schema-update
          reviewers: ainame
