name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Swiftly
        uses: vapor/swiftly-action@v0.2

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
