name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: ['6.1']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Swiftly
        uses: vapor/swiftly-action@v0.1
        with:
          toolchain: ${{ matrix.swift-version }}-RELEASE
      
      - name: Build
        run: swift build
      
      - name: Run tests
        run: swift test